version: '3'

services:
  # express server
  express-server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: '/app'
    volumes:
      - ./:/app  # sync data host <-> container
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis

  # nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - express-server

  # redis
  redis:
    image: redis:latest
    ports:
      - "6378:6379"

  # postgres
  postgres:
    image: postgres:latest
    container_name: express-postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
